### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maxence-lefebvre** [maxence-lefebvre/maxence-lefebvre#1]
- [ ] Write my personal profile
- [ ] Find a new name for the team
- [ ] Finish the new boilerplate from scratch 
- [ ] Add a create-*-boilerplate for yarn (without the hassle of react-scripts for now)
- [ ] Train Quackbot
- [ ] Add frontends for Quackbot

**Comment by sylvainar** [comment]
Consider adding `removing the chair joke in the readme` in this todo

**Comment by maxence-lefebvre** [comment]
> 
> 
> Consider adding `removing the chair joke in the readme` in this todo

Done
